// <auto-generated />
using System;
using LotLogic.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LotLogic.Api.Migrations
{
    [DbContext(typeof(LotLogicDbContext))]
    partial class LotLogicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("LotLogic.Core.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CheckInUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CheckOutUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LastFee")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalFees")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator<string>("VehicleType").HasValue("Vehicle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LotLogic.Core.Models.Car", b =>
                {
                    b.HasBaseType("LotLogic.Core.Models.Vehicle");

                    b.HasDiscriminator().HasValue("Car");
                });

            modelBuilder.Entity("LotLogic.Core.Models.Motorcycle", b =>
                {
                    b.HasBaseType("LotLogic.Core.Models.Vehicle");

                    b.HasDiscriminator().HasValue("Motorcycle");
                });
#pragma warning restore 612, 618
        }
    }
}
