// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrbanMobility.Api.Models;

#nullable disable

namespace UrbanMobility.Api.Migrations
{
    [DbContext(typeof(MobilityContext))]
    [Migration("20260404203553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("UrbanMobility.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Vehicle");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UrbanMobility.Api.Models.ElectricVehicle", b =>
                {
                    b.HasBaseType("UrbanMobility.Api.Models.Vehicle");

                    b.Property<double>("BatteryCapacityKwh")
                        .HasColumnType("REAL");

                    b.Property<int>("CurrentChargeLevel")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("ElectricVehicle");
                });

            modelBuilder.Entity("UrbanMobility.Api.Models.FuelVehicle", b =>
                {
                    b.HasBaseType("UrbanMobility.Api.Models.Vehicle");

                    b.Property<int>("Engine")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FuelTankSizeLiters")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("FuelVehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
