// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiBooksByIdFineData, GetApiBooksByIdFineResponses, GetApiBooksData, GetApiBooksResponses, PostApiBooksData, PostApiBooksResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiBooks = <ThrowOnError extends boolean = false>(options?: Options<GetApiBooksData, ThrowOnError>) => (options?.client ?? client).get<GetApiBooksResponses, unknown, ThrowOnError>({ url: '/api/books', ...options });

export const postApiBooks = <ThrowOnError extends boolean = false>(options: Options<PostApiBooksData, ThrowOnError>) => (options.client ?? client).post<PostApiBooksResponses, unknown, ThrowOnError>({
    url: '/api/books',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiBooksByIdFine = <ThrowOnError extends boolean = false>(options: Options<GetApiBooksByIdFineData, ThrowOnError>) => (options.client ?? client).get<GetApiBooksByIdFineResponses, unknown, ThrowOnError>({ url: '/api/books/{id}/fine', ...options });
