// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5275/' | (string & {});
};

export type CreateBookLoanRequest = {
    id: number | string;
    title: string;
    dueDate: string;
    returnedDate: null | string;
};

export type GetApiBooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/books';
};

export type GetApiBooksResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiBooksData = {
    body: CreateBookLoanRequest;
    path?: never;
    query?: never;
    url: '/api/books';
};

export type PostApiBooksResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiBooksByIdFineData = {
    body?: never;
    path: {
        id: number | string;
    };
    query?: never;
    url: '/api/books/{id}/fine';
};

export type GetApiBooksByIdFineResponses = {
    /**
     * OK
     */
    200: unknown;
};
